export const ADD_TO_CART = 'ADD_TO_CART';
export const RESET_QUANTITY = 'RESET_QUANTITY';
export const TOGGLE_ADDED_TO_CART = 'TOGGLE_ADDED_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_QUANTITY  = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY  = 'DECREASE_QUANTITY';
export const PAY_CART  = 'PAY_CART';